
Data encoding is the process of converting categorical features into numerical values so that models can understand and process them effectively. This is essential for tasks such as predicting salary based on categorical features like degree.

Types of Data Encoding
1. Nominal or One Hot Encoding
2. Label or Ordinal Encoding
3. Target Guided Ordinal Encoding

Nominal or One Hot Encoding
1. Consider a categorical feature called "color" with values such as red, green, and blue. This feature is categorical because it consists of distinct categories.
2. To enable the model to understand this feature, one hot encoding converts it into numerical features by creating new binary features for each category. For example, the categories red, green, and blue become three new features: red, green, and blue.
3. For each data point, the feature corresponding to its category is set to 1, and the others are set to 0. For instance, if the color is red, the red feature is 1, and green and blue are 0.

Disadvantages of One Hot Encoding
1. If a categorical feature has many categories, such as 100, one hot encoding will create 100 new features, increasing dimensionality.This leads to sparse matrices, where most values are zeros and only one value is one per row.
Sparse matrices can cause overfitting, where the model fits the training data too well but performs poorly on new data.
Therefore, one hot encoding is not recommended for features with many categories.

For example, a color variable with categories red, green, and blue can be represented as binary vectors such as 100, 010, and 001 respectively.

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
### create a dataframe
df = pd.DataFrame({"color": ["red", "blue", "green", "red", "blue"]})
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
### cretae an instance of one hot encoder
encoder=OneHotEncoder()

In [6]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

1. Label encoding and ordinal encoding are techniques to convert categorical data into numerical data for machine learning models.
2. Label encoding assigns unique numerical labels to each category, but may introduce unintended ordinal relationships.
3. Ordinal encoding is used when categorical variables have an intrinsic order or ranking, allowing explicit control over the ranking.
4. Using sklearn's LabelEncoder and OrdinalEncoder, encoding can be performed efficiently in Python.

In [12]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [18]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [19]:
lbl_encoder.fit_transform(df[['color']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [23]:
lbl_encoder.transform(['red'])
lbl_encoder.transform(['blue'])
lbl_encoder.transform(['green'])

array([1])

## limitations of Label Encoding
One problem with label encoding is that the model may interpret the numerical labels as having an order or ranking. For example, if red is assigned two, green is one, and blue is zero, the model may think red is greater than green and blue, which is not true for nominal data.

## Introduction to Ordinal Encoding
1. If you have a use case where you need to assign ranks to categories, you can use ordinal encoding. Ordinal encoding is used to encode categorical data that have an intrinsic order or ranking. Each category is assigned a numerical value based on its position in the order.

2. For example, if you have a categorical variable 'education level' with values like high school, college, graduate, and post graduate, you can represent it using ordinal encoding. High school can be rank one, college two, graduate three, and post graduate four.

In [24]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [35]:
encoded_df=encoder.fit_transform(df[['size']])

KeyError: "None of [Index(['size'], dtype='object')] are in the [columns]"