HANDLING IMBALANCED DATASET - 
1.UP SAMPLING
2.DOWN SAMPLING

In [7]:
import numpy as np
import pandas as pd

np.random.seed(0)

n_samples = 1000
class_zero_ratio = 0.9

n_class_zero = int(n_samples * class_zero_ratio)
n_class_one = n_samples - n_class_zero

In [8]:
n_class_zero,n_class_one

(900, 100)

In [9]:
# Generate features for class zero
feature1_class_zero = np.random.normal(loc=0, scale=1, size=n_class_zero)
feature2_class_zero = np.random.normal(loc=0, scale=1, size=n_class_zero)

# Generate features for class one
feature1_class_one = np.random.normal(loc=1, scale=1, size=n_class_one)
feature2_class_one = np.random.normal(loc=1, scale=1, size=n_class_one)

# Create dataframes
class_zero_df = pd.DataFrame({
    'feature1': feature1_class_zero,
    'feature2': feature2_class_zero,
    'target': 0
})

class_one_df = pd.DataFrame({
    'feature1': feature1_class_one,
    'feature2': feature2_class_one,
    'target': 1
})

# Combine dataframes
df = pd.concat([class_zero_df, class_one_df], ignore_index=True)

In [27]:
# Combine dataframes
df = pd.concat([class_zero_df, class_one_df]).reset_index(drop=True)

In [28]:
df.head()

   feature1  feature2  target
0  1.764052 -1.461733       0
1  0.400157 -0.683440       0
2  0.978738  0.367545       0
3  2.240893  0.190312       0
4  1.867558 -0.851729       0

In [29]:
df.tail()

     feature1  feature2  target
995  0.744529  1.097751       1
996  2.685792  2.401523       1
997 -0.648046  1.158434       1
998  1.298714 -0.141901       1
999  1.910646 -0.310970       1

In [30]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [31]:
### upsampling 
df_minority=df[df['target']==1]
df_majority=df[df['target']==1-0]

In [32]:
from sklearn.utils import resample
df_minority_upsampled = resample(
    df_minority,
    replace=True,  # sample with replacement
    n_samples=len(df_majority),  # match number in majority class
    random_state=42
)

In [33]:
df_minority_upsampled.shape

(100, 3)

In [34]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [35]:
df_upsampled['target'].value_counts()

target
1    200
Name: count, dtype: int64

In [36]:
df_majority_downsampled = resample(
    df_majority,
    replace=False,  # sample without replacement
    n_samples=len(df_minority),  # match number in minority class
    random_state=42
)

In [37]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority], ignore_index=True)

In [38]:
df_downsampled['target'].value_counts()

target
1    200
Name: count, dtype: int64