In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('feature_engineering_practice_dataset.csv')

In [4]:
df.head()

,age,salary,gender,department,education_level,experience_years,city,disease
0,56.0,23343.0,Male,Tech,Master,35,Bangalore,0
1,69.0,33500.0,Male,Sales,High School,7,Bangalore,0
2,46.0,73222.0,Male,Tech,Master,28,Bangalore,0
3,32.0,49375.0,Female,Tech,High School,31,Mumbai,0
4,60.0,29662.0,Female,Sales,High School,17,Bangalore,0

In [5]:
df.tail()

,age,salary,gender,department,education_level,experience_years,city,disease
495,65.0,139803.0,NaN,HR,High School,5,Delhi,0
496,42.0,90173.0,NaN,Finance,Master,31,Chennai,0
497,57.0,90390.0,Male,HR,Bachelor,28,Chennai,0
498,62.0,72329.0,Female,HR,Master,1,Chennai,0
499,NaN,142418.0,Male,Tech,Master,22,Bangalore,0

In [6]:
df.corr

<bound method DataFrame.corr of       age    salary  gender department education_level  experience_years  \
0    56.0   23343.0    Male       Tech          Master                35
1    69.0   33500.0    Male      Sales     High School                 7
2    46.0   73222.0    Male       Tech          Master                28
3    32.0   49375.0  Female       Tech     High School                31
4    60.0   29662.0  Female      Sales     High School                17
..    ...       ...     ...        ...             ...               ...
495  65.0  139803.0     NaN         HR     High School                 5
496  42.0   90173.0     NaN    Finance          Master                31
497  57.0   90390.0    Male         HR        Bachelor                28
498  62.0   72329.0  Female         HR          Master                 1
499   NaN  142418.0    Male       Tech          Master                22

          city  disease
0    Bangalore        0
1    Bangalore        0
2    Bangalore        0
3       Mumbai        0
4    Bangalore        0
..         ...      ...
495      Delhi        0
496    Chennai        0
497    Chennai        0
498    Chennai        0
499  Bangalore        0

[500 rows x 8 columns]>

In [7]:
df.isnull().sum()

age                 50
salary              49
gender              50
department           0
education_level      0
experience_years     0
city                 0
disease              0
dtype: int64

In [8]:
## using mean computation as the data in numerical form and data is normal
df['age'].fillna(df['age'].mean(),inplace=True)

C:\Users\lande\AppData\Local\Temp\ipykernel_10816\597245259.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)

In [9]:
df['salary'].fillna(df['salary'].mean(),inplace=True)

C:\Users\lande\AppData\Local\Temp\ipykernel_10816\1464685401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df['salary'].mean(),inplace=True)

In [10]:
### usinf mode computation for gender as it is categorical data
df['gender'].fillna(df['salary'].mode()[0],inplace=True)

C:\Users\lande\AppData\Local\Temp\ipykernel_10816\3946145627.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['salary'].mode()[0],inplace=True)

In [11]:
df.isnull().sum()

age                 0
salary              0
gender              0
department          0
education_level     0
experience_years    0
city                0
disease             0
dtype: int64

In [12]:
df.head(n=5)

,age,salary,gender,department,education_level,experience_years,city,disease
0,56.0,23343.0,Male,Tech,Master,35,Bangalore,0
1,69.0,33500.0,Male,Sales,High School,7,Bangalore,0
2,46.0,73222.0,Male,Tech,Master,28,Bangalore,0
3,32.0,49375.0,Female,Tech,High School,31,Mumbai,0
4,60.0,29662.0,Female,Sales,High School,17,Bangalore,0

### Handling imbalanced dataset

In [13]:
df['disease'].value_counts()

disease
0    428
1     72
Name: count, dtype: int64

In [14]:
df = pd.get_dummies(
    df,
    columns=['gender', 'department', 'education_level', 'city'],
    drop_first=True
)

In [15]:
## giving x and y value
X=df.drop('disease', axis=1)
y=df['disease']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [17]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [18]:
print(X_train_resampled,y_train_resampled)

           age         salary  experience_years  gender_Female  gender_Male  \
0    41.000000   67295.000000                22           True        False
1    23.000000   54578.000000                27          False         True
2    50.000000   82680.000000                22          False         True
3    36.000000   41732.000000                 9          False         True
4    21.000000   60158.000000                25          False         True
..         ...            ...               ...            ...          ...
679  65.394973   81913.036213                 5          False         True
680  60.532692   43324.875561                25           True         True
681  34.700779   69581.260306                 9           True         True
682  54.372538   43552.458999                32           True         True
683  42.247574  109180.351890                24           True         True

     department_HR  department_Sales  department_Tech  \
0            False             False            False
1            False             False            False
2            False              True            False
3            False             False            False
4            False              True            False
..             ...               ...              ...
679           True             False             True
680          False             False             True
681          False              True            False
682          False             False             True
683           True             False            False

     education_level_High School  education_level_Master  education_level_PhD  \
0                          False                    True                False
1                           True                   False                False
2                          False                   False                 True
3                          False                    True                False
4                          False                   False                 True
..                           ...                     ...                  ...
679                         True                   False                False
680                         True                   False                False
681                        False                    True                False
682                         True                   False                False
683                         True                    True                False

     city_Chennai  city_Delhi  city_Mumbai
0           False       False         True
1           False        True        False
2           False       False         True
3           False       False        False
4           False       False        False
..            ...         ...          ...
679         False        True         True
680          True        True        False
681          True        True        False
682          True        True        False
683          True        True        False

[684 rows x 14 columns] 0      0
1      0
2      0
3      0
4      0
      ..
679    1
680    1
681    1
682    1
683    1
Name: disease, Length: 684, dtype: int64

In [20]:
X_train_resampled.value_counts()

age        salary         experience_years  gender_Female  gender_Male  department_HR  department_Sales  department_Tech  education_level_High School  education_level_Master  education_level_PhD  city_Chennai  city_Delhi  city_Mumbai
18.000000  37100.000000   21                False          True         True           False             False            False                        False                   False                False         False       False          1
51.000000  27239.000000   29                True           False        False          False             True             False                        True                    False                True          False       False          1
50.000000  138874.000000  29                True           False        False          False             True             True                         False                   False                True          False       False          1
50.021989  123465.465467  19                True           False        True           False             False            False                        True                    False                False         True        True           1
50.065719  82535.038051   2                 False          True         True           False             True             True                         False                   False                True          False       True           1
                                                                                                                                                                                                                                            ..
39.764211  89955.403548   17                True           True         True           False             True             False                        True                    False                False         False       True           1
40.000000  24158.000000   29                True           False        True           False             False            True                         False                   False                False         False       True           1
           55735.000000   19                False          True         False          False             False            True                         False                   False                True          False       False          1
           67926.000000   38                False          False        False          True              False            False                        True                    False                False         False       True           1
69.000000  148778.000000  19                False          True         False          True              False            False                        True                    False                False         True        False          1
Name: count, Length: 684, dtype: int64

In [22]:
y_train_resampled.value_counts()

disease
0    342
1    342
Name: count, dtype: int64